package operation

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/anumey1/Suns/pkg/safety/floor"
	"github.com/anumey1/Suns/pkg/safety/identity"
)

// ServiceUnloadOp boots a launchd job out of its domain before its defining
// plist is removed by a separate FileDeleteOp (§12.3, §2.2). It is a pure value
// type so plan.Seal copies it without aliasing.
//
// Reversibility is Recoverable (🟡): the job can be re-loaded from its plist (or
// regenerated by its owning app). The plist file's own deletion is modeled
// separately as a FileDeleteOp; the engine emits this op BEFORE that delete so
// bootout always precedes removal.
type ServiceUnloadOp struct {
	Domain     string // launchd domain target, e.g. "gui/501" or "system"
	Label      string // the job label
	Plist      string // source plist path (identity + history)
	Privileged bool   // system-domain jobs require elevation
}

var _ Operation = ServiceUnloadOp{}

func (o ServiceUnloadOp) Kind() OpKind { return KindServiceUnload }

func (o ServiceUnloadOp) Reversibility() Reversibility { return Recoverable }

func (o ServiceUnloadOp) Describe() Preview {
	return Preview{
		Kind:          KindServiceUnload,
		Reversibility: Recoverable,
		Line:          fmt.Sprintf("bootout %s/%s  (%s)", o.Domain, o.Label, o.Plist),
	}
}

// ValidateAtPlan confirms the defining plist is off the deny floor and present.
func (o ServiceUnloadOp) ValidateAtPlan(ctx context.Context) error {
	if err := floor.Check(o.Plist); err != nil {
		return err
	}
	if _, err := os.Lstat(o.Plist); err != nil {
		return err
	}
	return nil
}

// ValidateAtExec re-confirms the defining plist still exists and returns the
// service identity (domain + label + source plist path, §2.2). If the plist has
// vanished the service definition is gone and the executor skips the op.
func (o ServiceUnloadOp) ValidateAtExec(ctx context.Context) (Identity, error) {
	if err := floor.Check(o.Plist); err != nil {
		return Identity{}, err
	}
	if _, err := os.Lstat(o.Plist); err != nil {
		return Identity{}, err
	}
	return Identity{
		Kind:    KindServiceUnload,
		Service: identity.ServiceIdent{Domain: o.Domain, Label: o.Label, Plist: o.Plist},
	}, nil
}

// Execute runs `launchctl bootout <domain>/<label>` through the injected system
// runner, elevating for system-domain jobs. A job that is already not loaded is
// treated as success (the desired end state), not a failure — bootout is
// best-effort by design. The deletion mode is inert for this op.
func (o ServiceUnloadOp) Execute(ctx context.Context, _ Mode, _ Identity) (Receipt, error) {
	r := Receipt{Kind: KindServiceUnload, Time: time.Now()}
	target := o.Domain + "/" + o.Label
	res, err := getSystemRunner().Run(ctx, o.Privileged, "launchctl", "bootout", target)
	switch {
	case err == nil && res.ExitCode == 0:
		r.Fate, r.Status = "unloaded", "ok"
	case err == ErrPrivilegeRequired:
		r.Fate, r.Status = "skipped", "skipped:no-privilege"
	case bootoutMissing(res):
		// Already not loaded: the end state we wanted is already true.
		r.Fate, r.Status = "unloaded", "ok:not-loaded"
	default:
		r.Fate, r.Status, r.Err = "skipped", "failed", err
	}
	return r, nil
}

func (o ServiceUnloadOp) HistoryRecord(r Receipt) HistoryEntry {
	return HistoryEntry{
		TS:         r.Time,
		Op:         KindServiceUnload,
		Reversible: Recoverable,
		Status:     r.Status,
		Domain:     o.Domain,
		Label:      o.Label,
		Plist:      o.Plist,
	}
}

// bootoutMissing reports whether launchctl failed only because the job was not
// loaded (across the various messages launchctl versions emit).
func bootoutMissing(res RunResult) bool {
	s := string(res.Stderr)
	for _, marker := range []string{
		"No such process",
		"Could not find",
		"not find specified service",
		"Boot-out failed",
		"No such file",
	} {
		if strings.Contains(s, marker) {
			return true
		}
	}
	return false
}
